server:
  port: 5444
  servlet:
    context-path: /

spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(TqfV6WVHROvDLKq/4sLEz658imEI+lJc3maek9Nm7DzjwDKjS/1YBsx0q8XCzJpogvfq3WEUmfno8RLL1FWDfcLQkXAh4c/sPhDeUId/YmBfz0fUKD+TK5y8RyagopHSJdmXxk6njkjPW7k92+3Kdbj2gDwcG9eZ4uzsmSxTsTocbLi5uDDyCRQLjQRoeL+t5mdOXZir++Q=)
    username: root
    password: ENC(RQBRaZSsYZ2XACRWqzPc1BWLcsY1Qfa5EHhq3Lbibqg=)
  # 热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/resources/static
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# mybatis 日志配置
mybatis:
  type-aliases-package: com.example.dict.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志文件的输入路径
logging:
  file:
    name: ./logs/log.out


# 文档工具
knife4j:
  # 开启增强配置
  enable: true
  # 开启Swagger的Basic认证功能,默认是false
  basic:
    enable: false
    # Basic认证用户名
    username: test
    # Basic认证密码
    password: 123
